### ISSUE TITLE
About adding highlighter brushes.

### ISSUE THREAD

**Issue by gmkzwwg** [szhielelp/JekyllTheme-ProjectGaia#5]
I tried  to apply the Bash SyntaxHighlighter brush. 
And I've added a new .js file in /js. 
But the site said "Can't find brush for: bash"
So how will it be?

And the navbar sometimes obstructs the right side of the article. I think it may have another interactive method rather than a show-hide button. I'll try to find more solutions like: hyalinize when the cursor is hovering over it; automatically indent.

jia you! xiong di ni tai you cai le.

**Comment by szhshp** [comment]
嘿！
那肯定是因为你没加个brush的js进去
[见这篇Doc](https://github.com/syntaxhighlighter/syntaxhighlighter/wiki/Brushes-and-Themes)
我的模板中偏偏没有bash的brush
所以只需要多加一个js然后pre tag里面的bash就会生效了


这一点我在Doc里面没有提到我之后会加上去


另外： 修改Transparency的方案我很喜欢，或许哪天我找个机会设计一下

**Comment by gmkzwwg** [comment]
恩谢谢解答~
主题很棒很喜欢
稍稍吐槽下这个语法高亮器迷之不全啊~我最近玩儿的Mozart Oz Idris以及之前玩的Lisp语系众甚至haskell prolog都没
/(ㄒoㄒ)/~~
不过想了一下有空可以自己contribute brush迷之带感。
设计大牛(*^__^*)

**Comment by szhshp** [comment]
比较小众的语言可能支持的情况较少，如果有更好的高亮插件完全可以推荐过来，不过当前架构只能用JS实现高亮就是

**Comment by gmkzwwg** [comment]
好像模板里的sh是3.0.83但是github上的版本已经到了4.0不太兼容造成的。。
抱歉但是(;´༎ຶД༎ຶ\`)。。。这个可以换回rouge嘛，我用到的语言基本都不支持(;´༎ຶД༎ຶ\`)
恩刚看到你的回复～我以前都是咸鱼一样地使用github pages自带的rouge～
试着改用rouge中。。
我是一匹js弱鸡，至今还没有搞清syntax highlighter是怎么作用的

**Comment by szhshp** [comment]
我找时间看看吧，确实该换个更好更通用的高亮插件了
不过一想到之前所有的用法都要改就背后一阵凉_(:з」∠)_

**Comment by szhielelp** [comment]
我找时间看看吧，确实该换个更好更通用的高亮插件了
不过一想到之前所有的用法都要改就背后一阵凉_(:з」∠)_

**Comment by gmkzwwg** [comment]
还好啦写个shell脚本用sed就可以自动全改掉，一次命令各种语言都可以替换～我去搞几个炫酷的配色方案～rouge最大的毛病就是不够炫酷中二

用这个就可以啦：
`sed 's/<pre class="brush: \([A-Za-z]*\)">/``` \1/'  <filename>`
`sed 's/<\/pre>/```/' <filename>`

**Comment by gmkzwwg** [comment]
我已经换成了rouge(｡・\`ω´･)自己DIY了一个黑客帝国风的配色(｡・\`ω´･)
顺便博客模板的/css/global.css里，body标签的背景的地址是网上的，没有使用img文件里的文件bg文件

**Comment by szhshp** [comment]
我想起来我当初就是因为rouge太丑才换的三方高亮引擎_(:з」∠)_
我之后也在这个模板里面加一些描述吧

**Comment by gmkzwwg** [comment]
恩是的是的，rouge自带的主题都太丑了太丑了（还不支持行号），我初步调了一下，有空继续弄几个主题。还有一个是，post.js里readingProgressBar就算调成了false,文章上方还会有一个post.css里的相应粗度的白条。

**Comment by gmkzwwg** [comment]
啊兄弟求个友站好伐，仔细看了你的主页发现竟然是全栈大手子！～我的是www.nekiri.com～

**Comment by szhshp** [comment]
行啊我这两天加上去，会日语的666

**Comment by gmkzwwg** [comment]
好的啦，对啦问下你的主页和about页面，内容分左右两栏是怎么做的呀～

**Comment by szhshp** [comment]
左右分两栏？
你是指内容各占50%屏幕？
那是通过bootstrap的Grid实现的，放两个各占一半的Grid Div
不知道你说的是不是这个？

**Comment by gmkzwwg** [comment]
嗯就是这个，谢谢你啦😜^_~

**Comment by szhshp** [comment]
这个解释起来有些麻烦了
你可以看看Bootstrap官方的[Grid Doc](https://v4-alpha.getbootstrap.com/layout/grid/)
里面应该有你想要的全部

**Comment by gmkzwwg** [comment]
恩好的辣，我看文档就好~
